### ISSUE TITLE
raw install has ray problem

### ISSUE THREAD

**Issue by EngrStudent** [werner-duvaud/muzero-general#198]
### Search before asking

- [X] I have searched the MuZero [issues](https://github.com/werner-duvaud/muzero-general/issues) and found no similar bug report.

### 🐛 Describe the bug

I created new venv, then installed per the requirements.  When I went to run "python muzero.py" it gave a repeating loop of ray errors.  

### Add an example

```
(raylet) /home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
(raylet)   warnings.warn(
(raylet) Traceback (most recent call last):
(raylet)   File "/home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 22, in <module>
(raylet)     import ray.new_dashboard.utils as dashboard_utils
(raylet)   File "/home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 20, in <module>
(raylet)     import aiohttp.signals
(raylet) ModuleNotFoundError: No module named 'aiohttp.signals'
(raylet) /home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
(raylet)   warnings.warn(
(raylet) Traceback (most recent call last):
(raylet)   File "/home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 22, in <module>
(raylet)     import ray.new_dashboard.utils as dashboard_utils
(raylet)   File "/home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 20, in <module>
(raylet)     import aiohttp.signals
(raylet) ModuleNotFoundError: No module named 'aiohttp.signals'
(raylet) /home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
(raylet)   warnings.warn(
(raylet) Traceback (most recent call last):
(raylet)   File "/home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 22, in <module>
(raylet)     import ray.new_dashboard.utils as dashboard_utils
(raylet)   File "/home/engrstudent/Documents/repositories/ml_on_preds/muzero-general-master/venv/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 20, in <module>
(raylet)     import aiohttp.signals
(raylet) ModuleNotFoundError: No module named 'aiohttp.signals'
```

### Environment

Here is my system information using 'inxi':
```
System:    Kernel: 5.4.0-113-generic x86_64 bits: 64 Desktop: Gnome 3.28.4
           Distro: Ubuntu 18.04.6 LTS
Machine:   Device: laptop System: CyberPowerPC product: Tracer III-XTREME 17R v: Standard serial: N/A
           Mobo: CyberPowerPC model: Tracer III-XTREME 17R v: Standard serial: N/A
           UEFI: American Megatrends v: N.1.03 date: 06/06/2019
Battery    BAT0: charge: 40.5 Wh 96.0% condition: 42.2/46.7 Wh (90%)
CPU:       6 core Intel Core i7-9750H (-MT-MCP-) cache: 12288 KB
           clock speeds: max: 4500 MHz 1: 800 MHz 2: 800 MHz 3: 800 MHz 4: 800 MHz 5: 800 MHz 6: 800 MHz
           7: 800 MHz 8: 800 MHz 9: 800 MHz 10: 800 MHz 11: 799 MHz 12: 800 MHz
Graphics:  Card-1: Intel Device 3e9b
           Card-2: NVIDIA Device 1e90
           Display Server: x11 (X.Org 1.20.8 ) drivers: modesetting,nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1920x1080@60.00hz, 1920x1080@144.00hz
           OpenGL: renderer: NVIDIA GeForce RTX 2080 with Max-Q Design/PCIe/SSE2 version: 4.6.0 NVIDIA 470.129.06
Audio:     Card-1 Intel Cannon Lake PCH cAVS driver: snd_hda_intel Sound: ALSA v: k5.4.0-113-generic
           Card-2 NVIDIA Device 10f8 driver: snd_hda_intel
Network:   Card-1: Intel Wireless-AC 9560 [Jefferson Peak] driver: iwlwifi
           IF: wlo1 state: up mac: 5c:87:9c:28:1a:ea
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
           IF: enp4s0 state: down mac: b0:25:aa:31:23:53
Drives:    HDD Total Size: 1086.2GB (52.6% used)
           ID-1: /dev/nvme0n1 model: INTEL_SSDPEKNW010T8 size: 1024.2GB
           ID-2: USB /dev/sdb model: USB_2.0_FD size: 62.0GB
Partition: ID-1: / size: 938G used: 515G (58%) fs: ext4 dev: /dev/nvme0n1p2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 45.0C mobo: N/A gpu: 39C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 454 Uptime: 18 days Memory: 5647.2/15861.2MB Client: Shell (bash) inxi: 2.3.56 

```

### Minimal Reproducible Example

I just ran the command "python muzero.py"

### Additional

I manually updated ray using "pip install ray --upgrade" and the warnings (and crashing) went away.

**Comment by digits122** [comment]
same error. Try this

pip uninstall ray
pip install "ray[default]"

use the newest version of ray instead of ray 1.5.2 version mentioned in requirements.lock and this problem solved.
