### ISSUE TITLE
muzero on Google Colab

### ISSUE THREAD

**Issue by charlesedwards** [werner-duvaud/muzero-general#28]
Hi there,

Great work on the repository.

Keen to try running on Google Colab, but run into an error on muzero.py.

Anyone had any luck getting to run on Google Colab?  

Thanks!

```

Welcome to MuZero! Here's a list of games:
0. cartpole
1. connect4
2. gomoku
3. lunarlander
4. tictactoe
Enter a number to choose the game: 0

0. Train
1. Load pretrained model
2. Render some self play games
3. Play against MuZero
4. Exit
Enter a number to choose an action: 0
2020-03-26 19:58:46,830	INFO resource_spec.py:212 -- Starting Ray with 6.64 GiB memory available for workers and up to 3.34 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-03-26 19:58:47,246	INFO services.py:1123 -- View the Ray dashboard at localhost:8265
2020-03-26 19:58:50,509	WARNING worker.py:1072 -- The dashboard on node 2fdf91b82296 failed with the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1062, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/dashboard/dashboard.py", line 920, in <module>
    dashboard.run()
  File "/usr/local/lib/python3.6/dist-packages/ray/dashboard/dashboard.py", line 368, in run
    aiohttp.web.run_app(self.app, host=self.host, port=self.port)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 433, in run_app
    reuse_port=reuse_port))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 359, in _run_app
    await site.start()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1066, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('::1', 8265, 0, 0): cannot assign requested address


Training...
Run tensorboard --logdir ./results and go to http://localhost:6006/ to see in real time the training performance.

2020-03-26 19:58:52,250	WARNING worker.py:1072 -- Failed to unpickle actor class 'Trainer' for actor ID 45b95b1c0100. Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/function_manager.py", line 494, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 1136, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'models'

(pid=630) 2020-03-26 19:58:52,240	ERROR function_manager.py:496 -- Failed to load actor class Trainer.
(pid=630) Traceback (most recent call last):
(pid=630)   File "/usr/local/lib/python3.6/dist-packages/ray/function_manager.py", line 494, in _load_actor_class_from_gcs
(pid=630)     actor_class = pickle.loads(pickled_class)
(pid=630)   File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle.py", line 1136, in subimport
(pid=630)     __import__(name)
(pid=630) ModuleNotFoundError: No module named 'models'
2020-03-26 19:58:52,733	WARNING worker.py:1072 -- WARNING: 6 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
---------------------------------------------------------------------------
RayTaskError(ModuleNotFoundError)         Traceback (most recent call last)
<ipython-input-6-b332aadb407c> in <module>()
    226         choice = int(choice)
    227         if choice == 0:
--> 228             muzero.train()
    229         elif choice == 1:
    230             path = input("Enter a path to the model.weights: ")

1 frames
/usr/local/lib/python3.6/dist-packages/ray/worker.py in get(object_ids, timeout)
   1500                     worker.core_worker.dump_object_store_memory_usage()
   1501                 if isinstance(value, RayTaskError):
-> 1502                     raise value.as_instanceof_cause()
   1503                 else:
   1504                     raise value

RayTaskError(ModuleNotFoundError): ray::IDLE (pid=631, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 430, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 433, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 434, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 306, in ray._raylet.deserialize_args
  File "/usr/local/lib/python3.6/dist-packages/ray/serialization.py", line 323, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/usr/local/lib/python3.6/dist-packages/ray/serialization.py", line 271, in _deserialize_object
    return self._deserialize_pickle5_data(data)
  File "/usr/local/lib/python3.6/dist-packages/ray/serialization.py", line 262, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
ModuleNotFoundError: No module named 'games'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by charlesedwards** [comment]
FYI - the Google Colab code used so you can replicate:

```
!git clone https://github.com/werner-duvaud/muzero-general.git

cd muzero-general

!pip install -r requirements.txt

!python muzero.py
```

**Comment by werner-duvaud** [comment]
Hi,

Thank you

Here is a [notebook](https://github.com/werner-duvaud/muzero-general/blob/master/notebook.ipynb) with which MuZero runs in Google Colab.

The first error `OSError: [Errno 99] error while attempting to bind on address ...` is normal, the creation of server does not work in Google Colab.

Do not hesitate if it still does not work for you.
