### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_global_worker'

### ISSUE THREAD

**Issue by drozzy** [werner-duvaud/muzero-general#3]
After about 40mins (it varies) of lunar lander training I get this error:

```
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>1791. Loss: 589.988
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fcaa87c17b8>
Traceback (most recent call last):
  File "/home/andriy/miniconda3/envs/muzero/lib/python3.7/site-packages/ray/actor.py", line 652, in __del__
AttributeError: 'NoneType' object has no attribute 'get_global_worker'

```

**Comment by werner-duvaud** [comment]
I cannot reproduce the bug and the error implies ray and is not very informative.

Did you modify the code by adding Tune? It might look like this: https://github.com/ray-project/ray/issues/5042.

**Comment by drozzy** [comment]
I didn't modify the code at all here, just running it as it came from the repo, on ubuntu 19, in conda env.
