### ISSUE TITLE
Retrying to connect to socket for pathname tcp://127.0.0.1:54380

### ISSUE THREAD

**Issue by seboz123** [werner-duvaud/muzero-general#58]
Hi, 

I cloned your repo and tried to use it with a fresh environment. Unfortunately, it seems that it does not work properly, as I get the following error when trying to train or play against muzero:

```
(muzero) C:\Users\...\Desktop\RLUnity\python\muzero-general>python muzero.py

Welcome to MuZero! Here's a list of games:
0. breakout
1. cartpole
2. connect4
3. gomoku
4. gridworld
5. lunarlander
6. tictactoe
7. twentyone
Enter a number to choose the game: 0

0. Train
1. Load pretrained model
2. Diagnose model
3. Render some self play games
4. Play against MuZero
5. Test the game manually
6. Exit
Enter a number to choose an action: 4

Testing...
2020-07-03 13:48:15,208 INFO resource_spec.py:212 -- Starting Ray with 6.49 GiB memory available for workers and up to 3.26 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-07-03 13:48:15,637 INFO services.py:1165 -- View the Ray dashboard at [1m[32mlocalhost:8265[39m[22m
E0703 13:48:20.680589 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 1, num_retries = 10)
E0703 13:48:23.682262 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 2, num_retries = 10)
E0703 13:48:26.682521 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 3, num_retries = 10)
E0703 13:48:29.685930 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 4, num_retries = 10)
E0703 13:48:32.687705 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 5, num_retries = 10)
E0703 13:48:35.690719 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 6, num_retries = 10)
E0703 13:48:38.692248 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 7, num_retries = 10)
E0703 13:48:41.694942 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 8, num_retries = 10)
E0703 13:48:44.696983 13144 11520 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:60437 (num_attempts = 9, num_retries = 10)
F0703 13:48:45.697768 13144 11520 raylet_client.cc:78] Could not connect to socket tcp://127.0.0.1:60437
*** Check failure stack trace: ***
    @   00007FFDB9633A8C  public: __cdecl google::LogMessage::~LogMessage(void) __ptr64
    @   00007FFDB94A8954  public: virtual __cdecl google::NullStreamFatal::~NullStreamFatal(void) __ptr64
    @   00007FFDB94E351B  public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
    @   00007FFDB94E5B5E  public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
    @   00007FFDB93F3B98  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
    @   00007FFDB93F1C00  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
    @   00007FFDB93F00ED  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
    @   00007FFDB93EF9C3  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
    @   00007FFDB936F179  public: virtual __cdecl google::LogSink::~LogSink(void) __ptr64
    @   00007FFDF395F9CF  _PyObject_FastCallKeywords
    @   00007FFDF395F7DA  _PyObject_FastCallKeywords
    @   00007FFDF3967939  _PyMethodDef_RawFastCallKeywords
    @   00007FFDF3968322  _PyEval_EvalFrameDefault
    @   00007FFDF3951286  _PyEval_EvalCodeWithName
    @   00007FFDF3967907  _PyMethodDef_RawFastCallKeywords
    @   00007FFDF3968A69  _PyEval_EvalFrameDefault
    @   00007FFDF3A523A3  _PyStack_UnpackDict
    @   00007FFDF39AB431  PyErr_NoMemory
    @   00007FFDF3968322  _PyEval_EvalFrameDefault
    @   00007FFDF3951286  _PyEval_EvalCodeWithName
    @   00007FFDF3967907  _PyMethodDef_RawFastCallKeywords
    @   00007FFDF3968A69  _PyEval_EvalFrameDefault
    @   00007FFDF3951286  _PyEval_EvalCodeWithName
    @   00007FFDF3932A93  PyEval_EvalCodeEx
    @   00007FFDF39329F1  PyEval_EvalCode
    @   00007FFDF393299B  PyArena_Free
    @   00007FFDF3AC614D  PyRun_FileExFlags
    @   00007FFDF3AC6974  PyRun_SimpleFileExFlags
    @   00007FFDF3AC601B  PyRun_AnyFileExFlags
    @   00007FFDF3A11AAF  _Py_UnixMain
    @   00007FFDF3A11B57  _Py_UnixMain
    @   00007FFDF3980D5A  PyErr_NoMemory
```

Also I experienced an Error when trying to run breakout. I needed to install gym[atari] in addition to the requirements.

```
(muzero) C:\Users\...\Desktop\RLUnity\python\muzero-general>python muzero.py

Welcome to MuZero! Here's a list of games:
0. breakout
1. cartpole
2. connect4
3. gomoku
4. gridworld
5. lunarlander
6. tictactoe
7. twentyone
Enter a number to choose the game: 0
breakout is not a supported game name, try "cartpole" or refer to the documentation for adding a new game.
Traceback (most recent call last):
  File "C:\Users\...\Desktop\RLUnity\python\muzero-general\games\breakout.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "muzero.py", line 286, in <module>
    muzero = MuZero(games[choice])
  File "muzero.py", line 48, in __init__
    raise err
  File "muzero.py", line 39, in __init__
    game_module = importlib.import_module("games." + self.game_name)
  File "C:\Users\...\.conda\envs\muzero\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\...\Desktop\RLUnity\python\muzero-general\games\breakout.py", line 13, in <module>
    raise ModuleNotFoundError('Please run "pip install gym[atari]"')
ModuleNotFoundError: Please run "pip install gym[atari]"

```

**Comment by werner-duvaud** [comment]
Hi,

About the first error, it does not seem to concern MuZero directly but more Ray.
Are you on Windows with WSL? Ray is just starting to be compatible on Windows, it remains experimental.

Regarding the second error, it is done on purpose, we prefer not to force systematically to install dependencies for Atari since they are specific to a single environment.

**Comment by seboz123** [comment]
I am just using windows 10. Should I be using WSL or linux directly?

**Comment by werner-duvaud** [comment]
Linux directly or Mac (until ray is fully compatible with Windows.)

**Comment by seboz123** [comment]
Thank you
